-- 코드를 입력하세요
SELECT DATE_FORMAT(N.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, N.PRODUCT_ID, N.USER_ID, N.SALES_AMOUNT
from
ONLINE_SALE N
WHERE N.SALES_DATE >= '2022-03-01' AND N.SALES_DATE < '2022-04-01'

UNION ALL

SELECT DATE_FORMAT(F.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, F.PRODUCT_ID, NULL, F.SALES_AMOUNT
from
OFFLINE_SALE F
WHERE F.SALES_DATE >= '2022-03-01' AND F.SALES_DATE < '2022-04-01'

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;