-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, 
CONCAT(U.CITY, ' ', U.STREET_ADDRESS1, ' ', U.STREET_ADDRESS2) AS 전체주소, 
CONCAT(LEFT(TLNO,3),'-',LEFT(RIGHT(TLNO,8),4),'-',RIGHT(TLNO,4)) AS 전화번호
FROM USED_GOODS_USER U
JOIN
(
SELECT WRITER_ID
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID
HAVING COUNT(*) >= 3) AS B
ON U.USER_ID = B.WRITER_ID
ORDER BY USER_ID DESC